name: Deploy to Cloudflare Pages

on:
  schedule:
    - cron: '0 */5 * * *' # 每 5 小时执行一次
  workflow_dispatch:
    inputs:
      build_type:
        description: Type of build (e.g., 'deploy', 'test')
        required: true
        type: choice
        options:
          - deploy
          - test


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 添加构建步骤（例如，安装依赖、运行构建）
      - name: Install dependencies
        run: yarn install
        if: inputs.build_type == 'deploy' # 仅在部署时执行

      - name: Run build command (test)
        run: yarn export --test # 注意 --test 的存在
        if: inputs.build_type == 'test'

      - name: Run build command (deploy)
        run: yarn export
        if: inputs.build_type == 'deploy'

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: notionnext # 你的 Cloudflare Pages 项目名称

