name: Update Requirements

on:
  schedule:
    - cron: '0 */5 * * *' 

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: mine # 替换成你的分支名称

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # 设置你的 Python 版本

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update requirements
        run: pip freeze > requirements.txt

      - name: Commit changes
        uses: stefcurry/git-push-action@v4
        with:
          branch: mine # 替换成你的分支名称
          commit_message: "Update requirements.txt"
